name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Allure Commandline
      run: npm install -g allure-commandline --save-dev

    - name: Run Playwright tests
      run: npx playwright test
      continue-on-error: true  # Ensures the job doesn't stop if there are failures

    - name: Generate Allure report
      run: allure generate ./allure-results --clean -o ./allure-report

    - name: Rename index.html with build number
      run: |
        BUILD_NUMBER=${{ github.run_id }}
        mv allure-report/index.html allure-report/${BUILD_NUMBER}.html

    - name: Gather all test reports
      run: |
        mkdir -p gh-pages/reports/${{ github.run_id }}
        cp -r allure-report/* gh-pages/reports/${{ github.run_id }}/
        mv gh-pages/reports/${{ github.run_id }}/index.html gh-pages/reports/${{ github.run_id }}/index.html
        mkdir -p gh-pages/reports/latest
        cp -r gh-pages/reports/${{ github.run_id }}/index.html gh-pages/reports/latest/

    - name: Push Playwright report to GitHub Pages
      run: |
        mkdir -p gh-pages
        cp -r gh-pages/reports/* gh-pages/

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        cd gh-pages
        git init
        git add .
        git commit -m "Add Playwright test report"

        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git checkout -b gh-pages
        git push --force --set-upstream origin gh-pages

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
