name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Push Playwright report to GitHub Pages
      run: |
        # Create a new directory for GitHub Pages
        mkdir gh-pages
        
        # Copy the test report files into that directory
        cp -r playwright-report/* gh-pages/

        # Set GitHub Actions as the committer
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Initialize a new Git repository and commit the files
        git init
        git add .
        git commit -m "Add Playwright test report"

        # Push the commit to the gh-pages branch (force push)
        git remote add origin https://github.com/${{ github.repository }}.git
        git push --force --set-upstream origin gh-pages

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
